
PHONY: tweets snake clean

snake:
	gcc -Wall markov_chain.c markov_chain.h linked_list.h linked_list.c s\
nakes_and_ladders.c -o snakes_and_ladders.o

tweets:
	gcc -Wall markov_chain.c markov_chain.h linked_list.h linked_list.c \
tweets_generator.c -o tweets_generator.o

clean:
	rm tweets_generator.o snakes_and_ladders.o